export interface SchemeItem {
  id: string;
  icon: string;
  title: string;
  titleNative?: Record<string, string>;
  state: string;
  category: "Financial Assistance" | "Insurance" | "Irrigation" | "Crop & Seeds" | "Equipment" | "Horticulture" | "Credit & Loans" | "Solar & Energy";
  coverage: string;
  benefit: string;
  documentsCount: number;
  description: string;
  officialUrl: string;
  eligibility: string[];
  documentsList: string[];
  howToApply: string;
}

export const ALL_GOVERNMENT_SCHEMES: SchemeItem[] = [
  {
    id: "pm-kisan",
    icon: "💰",
    title: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "All India",
    benefit: "Direct income support through DBT as per current PM-KISAN guidelines (₹6,000/yr in 3 installments).",
    documentsCount: 5,
    description: "Central Sector Scheme providing income support to eligible landholding farmer families according to Government of India guidelines.",
    officialUrl: "https://pmkisan.gov.in",
    eligibility: ["Landholding farmer families with cultivable land record", "Aadhaar-linked active bank account", "Completed mandatory e-KYC on PM-KISAN portal"],
    documentsList: ["Aadhaar Card", "Land Ownership Record (Patta/Khata/7/12)", "Bank Passbook with IFSC", "Active Mobile Number", "Citizenship/Residence Proof"],
    howToApply: "Visit pmkisan.gov.in -> Farmers Corner -> New Farmer Registration, or visit your nearest CSC / Rythu Bharosa Kendra."
  },
  {
    id: "pmfby",
    icon: "🛡️",
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    state: "All India",
    category: "Insurance",
    coverage: "All India",
    benefit: "Crop insurance protection according to the notified crops, areas and applicable season guidelines.",
    documentsCount: 8,
    description: "Crop insurance scheme providing financial protection to farmers against specified crop losses and risks.",
    officialUrl: "https://pmfby.gov.in",
    eligibility: ["All farmers growing notified crops in notified areas (both loanee & non-loanee farmers)", "Sharecroppers and tenant farmers eligible with certificate"],
    documentsList: ["Aadhaar Card", "Land Record / Tenancy Agreement", "Bank Account Details", "Sowing Certificate / Crop Sowing Declaration", "Identity Proof", "Address Proof", "Cancelled Cheque", "Kisan Credit Card (if loanee)"],
    howToApply: "Apply online at pmfby.gov.in or through bank branches, Primary Agricultural Credit Societies (PACS), or CSC centres."
  },
  {
    id: "pm-kmy",
    icon: "💰",
    title: "Pradhan Mantri Kisan Maan Dhan Yojana (PM-KMY)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "All India",
    benefit: "Pension support according to the PM-KMY rules (guaranteed ₹3,000/month after age 60).",
    documentsCount: 2,
    description: "Pension scheme for eligible small and marginal farmers.",
    officialUrl: "https://maandhan.in",
    eligibility: ["Small and marginal farmers aged 18 to 40 years", "Cultivable land up to 2 hectares (5 acres)", "Monthly contribution ₹55 to ₹200 based on entry age"],
    documentsList: ["Aadhaar Card", "Savings Bank Account / Jan Dhan Account with IFSC"],
    howToApply: "Visit nearest Common Service Centre (CSC) or apply on maandhan.in."
  },
  {
    id: "pmksy",
    icon: "💧",
    title: "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)",
    state: "All India",
    category: "Irrigation",
    coverage: "All India",
    benefit: "Support under applicable irrigation and water-use-efficiency components (up to 55%-90% subsidy on drip/sprinkler).",
    documentsCount: 2,
    description: "Government programme focused on improving irrigation coverage and water-use efficiency in agriculture.",
    officialUrl: "https://pmksy.gov.in",
    eligibility: ["Farmers with cultivable agricultural land with an assured water source", "Priority to small and marginal farmers, SC/ST, and women farmers"],
    documentsList: ["Land Ownership Records (ROR/Khatauni)", "Aadhaar Card & Bank Details"],
    howToApply: "Apply via state horticulture/agriculture portal or visit District Agriculture Office."
  },
  {
    id: "rkvy-central",
    icon: "💰",
    title: "Rashtriya Krishi Vikas Yojana (RKVY)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "All India",
    benefit: "Benefits depend on the approved state and project components.",
    documentsCount: 2,
    description: "Agriculture development programme supporting state-level agricultural development interventions.",
    officialUrl: "https://rkvy.nic.in",
    eligibility: ["Farmer groups, FPOs, Agri-entrepreneurs, and individual cultivators under state-approved projects"],
    documentsList: ["Farmer / FPO Registration Proof", "Bank Account Details & Land Records"],
    howToApply: "Submit project proposals or scheme applications to State Agriculture Department / ATMA."
  },
  {
    id: "nfsm-central",
    icon: "🌱",
    title: "National Food Security Mission (NFSM)",
    state: "All India",
    category: "Crop & Seeds",
    coverage: "Participating states and notified areas",
    benefit: "Support depends on crop, component and applicable state guidelines (seed minikits, micronutrients, field demonstrations).",
    documentsCount: 2,
    description: "Mission supporting production and productivity of selected food crops.",
    officialUrl: "https://nfsm.gov.in",
    eligibility: ["Farmers cultivating food grains, pulses, millets, and oilseeds in identified districts"],
    documentsList: ["Aadhaar Card", "Land Record / Cultivation Proof"],
    howToApply: "Contact Block Agriculture Officer / KVK for seed kits and demonstration inclusion."
  },
  {
    id: "smam-central",
    icon: "🚜",
    title: "Sub-Mission on Agricultural Mechanization (SMAM)",
    state: "All India",
    category: "Equipment",
    coverage: "Participating states",
    benefit: "Assistance depends on the machinery and component approved under current guidelines (40%-50% subsidy on tractors, tillers, harvesters).",
    documentsCount: 2,
    description: "Programme supporting agricultural mechanization and improved access to farm machinery.",
    officialUrl: "https://agrimachinery.nic.in",
    eligibility: ["Individual farmers, Custom Hiring Centres (CHC), and Farmer Producer Organizations (FPOs)"],
    documentsList: ["Aadhaar Card", "Land Records / Passbook copy"],
    howToApply: "Register on Direct Benefit Transfer in Agricultural Mechanization portal: agrimachinery.nic.in."
  },
  {
    id: "pkvy-central",
    icon: "🌱",
    title: "Paramparagat Krishi Vikas Yojana (PKVY)",
    state: "All India",
    category: "Crop & Seeds",
    coverage: "Participating states",
    benefit: "Support according to applicable organic farming programme guidelines (₹50,000/ha for cluster formation & organic inputs).",
    documentsCount: 2,
    description: "Programme supporting organic and sustainable farming practices.",
    officialUrl: "https://pgsindia-ncof.gov.in",
    eligibility: ["Farmers willing to form clusters of 20 or more farmers adopting PGS organic certification"],
    documentsList: ["Aadhaar Card", "Land Records & Cluster Membership Form"],
    howToApply: "Apply through Regional Council or District Agriculture Office for PGS-India registration."
  },
  {
    id: "aif-central",
    icon: "💰",
    title: "Agriculture Infrastructure Fund (AIF)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "All India",
    benefit: "Financing support according to Agriculture Infrastructure Fund guidelines (3% interest subvention for post-harvest infrastructure loans up to ₹2 Crore).",
    documentsCount: 2,
    description: "Financing facility supporting agricultural infrastructure and related projects.",
    officialUrl: "https://agriinfra.dac.gov.in",
    eligibility: ["Farmers, Agri-entrepreneurs, FPOs, PACS, SHGs, Startups"],
    documentsList: ["DPR (Detailed Project Report)", "Aadhaar, PAN & Bank Details"],
    howToApply: "Apply online at agriinfra.dac.gov.in."
  },
  {
    id: "atma-central",
    icon: "🌱",
    title: "Agricultural Technology Management Agency (ATMA)",
    state: "All India",
    category: "Crop & Seeds",
    coverage: "Participating districts",
    benefit: "Agricultural extension, training and technology-related support.",
    documentsCount: 2,
    description: "Agricultural extension programme supporting farmer training, demonstrations and technology dissemination.",
    officialUrl: "https://extensionreforms.gov.in",
    eligibility: ["All practicing farmers and commodity interest groups"],
    documentsList: ["Aadhaar Card", "Farmer ID"],
    howToApply: "Register at your block ATMA office / Kisan Seva Kendra."
  },
  {
    id: "enam-central",
    icon: "💰",
    title: "National Agriculture Market (e-NAM)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "Participating markets across India",
    benefit: "Online market-related services and access to participating agricultural markets across India.",
    documentsCount: 2,
    description: "National electronic agriculture market platform connecting agricultural markets.",
    officialUrl: "https://enam.gov.in",
    eligibility: ["All farmers bringing produce to registered APMC mandis"],
    documentsList: ["Aadhaar Card", "Bank Account Passbook"],
    howToApply: "Register at enam.gov.in or at the gate of any e-NAM enabled APMC Mandi."
  },

  // ANDHRA PRADESH SCHEMES
  {
    id: "ap-soil-health",
    icon: "🌱",
    title: "Soil Health Card Scheme",
    state: "Andhra Pradesh",
    category: "Crop & Seeds",
    coverage: "Andhra Pradesh",
    benefit: "Soil health information and recommendations for appropriate nutrient management.",
    documentsCount: 2,
    description: "Soil testing and soil health information programme providing crop-wise nutrient recommendations.",
    officialUrl: "https://soilhealth.dac.gov.in",
    eligibility: ["All agricultural landholders in Andhra Pradesh"],
    documentsList: ["Aadhaar Card", "Survey Number / Land Passbook"],
    howToApply: "Soil samples collected by Village Agriculture Assistants at Rythu Bharosa Kendras (RBKs)."
  },
  {
    id: "ap-seed-subsidy",
    icon: "🌱",
    title: "Distribution of Seed on Subsidy",
    state: "Andhra Pradesh",
    category: "Crop & Seeds",
    coverage: "Andhra Pradesh",
    benefit: "Seed support according to applicable crop and government guidelines (up to 50% subsidy on certified seeds).",
    documentsCount: 2,
    description: "Government programme for distribution of agricultural seed to farmers with subsidy support.",
    officialUrl: "https://apagrisnet.gov.in",
    eligibility: ["Registered farmers in Andhra Pradesh with e-Crop booking"],
    documentsList: ["Aadhaar Card", "e-Crop Booking Reference"],
    howToApply: "Book seed varieties through Rythu Bharosa Kendras (RBK) before the Kharif/Rabi season."
  },
  {
    id: "ap-seed-village",
    icon: "🌱",
    title: "Seed Village Scheme",
    state: "Andhra Pradesh",
    category: "Crop & Seeds",
    coverage: "Andhra Pradesh",
    benefit: "Support for improving availability of quality seed.",
    documentsCount: 2,
    description: "Seed production and availability programme listed by the Andhra Pradesh Agriculture Department.",
    officialUrl: "https://apagrisnet.gov.in",
    eligibility: ["Farmers in identified seed production clusters"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Contact Assistant Director of Agriculture (ADA) in the district."
  },
  {
    id: "ap-natural-farming",
    icon: "🌱",
    title: "Natural Farming (APCNF)",
    state: "Andhra Pradesh",
    category: "Crop & Seeds",
    coverage: "Andhra Pradesh",
    benefit: "Support and extension services according to the applicable natural farming programme.",
    documentsCount: 2,
    description: "Natural farming programme listed by the Andhra Pradesh Agriculture Department.",
    officialUrl: "https://apcnf.in",
    eligibility: ["All farmers adopting chemical-free Zero Budget Natural Farming"],
    documentsList: ["Aadhaar Card", "Farmer ID"],
    howToApply: "Register with local Community Resource Persons (CRPs) at the village RBK."
  },
  {
    id: "ap-rkvy-machinery",
    icon: "🚜",
    title: "RKVY - Farm Machinery Support",
    state: "Andhra Pradesh",
    category: "Equipment",
    coverage: "Andhra Pradesh",
    benefit: "Machinery support according to the applicable RKVY component and government guidelines.",
    documentsCount: 2,
    description: "RKVY component supporting access to high-cost farm machinery through community and hiring-centre arrangements.",
    officialUrl: "https://apagrisnet.gov.in",
    eligibility: ["Farmer groups (Rythu Mithra Groups) and individual progressive farmers"],
    documentsList: ["Group Registration / Aadhaar", "Land Records"],
    howToApply: "Apply online on the AP Agrisnet portal or at District Collectorate Agriculture Department."
  },
  {
    id: "ap-apmip-irrigation",
    icon: "💧",
    title: "Andhra Pradesh Micro Irrigation Project (APMIP)",
    state: "Andhra Pradesh",
    category: "Irrigation",
    coverage: "Andhra Pradesh",
    benefit: "Micro-irrigation assistance according to current APMIP guidelines (90% subsidy for SC/ST, 70% for Small/Marginal).",
    documentsCount: 2,
    description: "Programme promoting adoption of micro-irrigation technologies to improve water-use efficiency.",
    officialUrl: "https://apmip.ap.gov.in",
    eligibility: ["Farmers with borewell or open well having electrical connection"],
    documentsList: ["Pattadar Passbook / 1-B Adangal", "Aadhaar Card"],
    howToApply: "Apply online at apmip.ap.gov.in or through RBK Village Agriculture Assistant."
  },

  // TAMIL NADU SCHEMES
  {
    id: "tn-smam",
    icon: "🚜",
    title: "Sub-Mission on Agricultural Mechanisation",
    state: "Tamil Nadu",
    category: "Equipment",
    coverage: "Tamil Nadu",
    benefit: "Mechanisation assistance according to the applicable component (subsidies up to 50% on agricultural machinery).",
    documentsCount: 2,
    description: "Tamil Nadu Agriculture Department programme aimed at increasing access to agricultural mechanisation, particularly for farmers.",
    officialUrl: "https://aed.tn.gov.in",
    eligibility: ["Farmers in Tamil Nadu owning cultivable lands"],
    documentsList: ["Chitta / Adangal", "Aadhaar Card"],
    howToApply: "Apply on the Uzhavan App or via the Agricultural Engineering Department website."
  },
  {
    id: "tn-mannuyir-kaathu",
    icon: "🌱",
    title: "Chief Minister's Mannuyir Kaathu Mannuyir Kaappom Scheme",
    state: "Tamil Nadu",
    category: "Crop & Seeds",
    coverage: "Tamil Nadu",
    benefit: "Benefits depend on the applicable programme component (soil organic enrichment, green manure seeds).",
    documentsCount: 2,
    description: "Tamil Nadu government agriculture programme listed in the official Agriculture Department scheme database.",
    officialUrl: "https://agritech.tnau.ac.in",
    eligibility: ["All farming households in rural Tamil Nadu"],
    documentsList: ["Aadhaar Card", "Land Patta"],
    howToApply: "Contact Block Agricultural Extension Centre (AEC) or apply through Uzhavan App."
  },
  {
    id: "tn-tniamp",
    icon: "💰",
    title: "Tamil Nadu Irrigated Agriculture Modernisation Project (TNIAMP)",
    state: "Tamil Nadu",
    category: "Financial Assistance",
    coverage: "Tamil Nadu",
    benefit: "Capital subsidy according to the current TNIAMP component and guidelines.",
    documentsCount: 2,
    description: "Programme supporting agri entrepreneurship, value addition, processing and packaging activities.",
    officialUrl: "https://iamwarm.gov.in",
    eligibility: ["Farmers in 66 selected sub-basins of Tamil Nadu"],
    documentsList: ["Aadhaar Card", "Land Document & Sub-basin verification"],
    howToApply: "Submit application to Assistant Director of Agriculture in the designated river basin."
  },
  {
    id: "tn-kaviadp",
    icon: "🌱",
    title: "Kalaignar's All Village Integrated Agriculture Development Programme (KAVIADP)",
    state: "Tamil Nadu",
    category: "Crop & Seeds",
    coverage: "Tamil Nadu",
    benefit: "Agricultural input and crop development support according to programme components.",
    documentsCount: 2,
    description: "Integrated village agriculture development programme implemented by Tamil Nadu.",
    officialUrl: "https://tnagrisnet.tn.gov.in",
    eligibility: ["Farmers in notified Gram Panchayats selected under KAVIADP"],
    documentsList: ["Aadhaar Card", "Ration Card", "Land Records"],
    howToApply: "Participate in Gram Sabha meetings and register at the local Agricultural Extension Centre."
  },
  {
    id: "tn-rad-ifs",
    icon: "🌱",
    title: "Rainfed Area Development - Integrated Farming System",
    state: "Tamil Nadu",
    category: "Crop & Seeds",
    coverage: "Tamil Nadu",
    benefit: "Support according to the applicable Rainfed Area Development component (up to ₹50,000 for IFS units combining crops, dairy, and apiary).",
    documentsCount: 2,
    description: "Integrated farming system programme for rainfed agricultural areas.",
    officialUrl: "https://tnagrisnet.tn.gov.in",
    eligibility: ["Rainfed farmers owning minimum 1 hectare land"],
    documentsList: ["Patta / Chitta", "Aadhaar Card"],
    howToApply: "Apply to District Joint Director of Agriculture."
  },
  {
    id: "tn-pmksy-micro",
    icon: "💧",
    title: "PMKSY - Micro Irrigation",
    state: "Tamil Nadu",
    category: "Irrigation",
    coverage: "Tamil Nadu",
    benefit: "Micro-irrigation assistance according to applicable guidelines (100% subsidy for Small/Marginal farmers, 75% for others).",
    documentsCount: 2,
    description: "Micro-irrigation programme promoting efficient use of water resources.",
    officialUrl: "https://tnhorticulture.tn.gov.in",
    eligibility: ["Horticulture and agricultural crop growers in Tamil Nadu"],
    documentsList: ["Patta / Chitta", "Aadhaar Card & Water Source Certificate"],
    howToApply: "Apply on tnhorticulture.tn.gov.in or visit Assistant Director of Horticulture."
  },
  {
    id: "tn-solar-drying",
    icon: "🚜",
    title: "Installation of Solar Drying Unit",
    state: "Tamil Nadu",
    category: "Equipment",
    coverage: "Tamil Nadu",
    benefit: "Subsidy assistance according to the current Tamil Nadu Agricultural Engineering scheme (up to 40%-50% capital subsidy).",
    documentsCount: 2,
    description: "Subsidy assistance for solar drying units to reduce post-harvest losses and support value addition.",
    officialUrl: "https://aed.tn.gov.in",
    eligibility: ["Individual farmers, farmer groups, and self-help groups"],
    documentsList: ["Aadhaar Card", "Land Document"],
    howToApply: "Apply at Agricultural Engineering Department, Chennai / District Executive Engineer office."
  },
  {
    id: "tn-solar-fencing",
    icon: "🚜",
    title: "Installation of Solar Fencing Unit",
    state: "Tamil Nadu",
    category: "Equipment",
    coverage: "Tamil Nadu",
    benefit: "Subsidy assistance according to the current scheme guidelines (protects crops against wild animals).",
    documentsCount: 2,
    description: "Solar fencing assistance for protecting agricultural land in applicable areas.",
    officialUrl: "https://aed.tn.gov.in",
    eligibility: ["Farmers whose lands border forest areas and wildlife corridors"],
    documentsList: ["Aadhaar Card", "Patta / Chitta"],
    howToApply: "Submit application to Agricultural Engineering Department."
  },
  {
    id: "tn-value-addition",
    icon: "🚜",
    title: "Value Addition Machinery Facilitation Centre",
    state: "Tamil Nadu",
    category: "Equipment",
    coverage: "Tamil Nadu",
    benefit: "Subsidy assistance according to the current scheme component for post-harvest equipment.",
    documentsCount: 2,
    description: "Programme supporting farmer groups with machinery for agricultural value addition.",
    officialUrl: "https://aed.tn.gov.in",
    eligibility: ["Farmer Producer Companies (FPCs) and registered farmer societies"],
    documentsList: ["Society Registration", "Aadhaar of office bearers"],
    howToApply: "Apply through District Agri Engineering Department."
  },
  {
    id: "tn-npop-cert",
    icon: "🌱",
    title: "National Programme for Organic Production (NPOP) Certification",
    state: "Tamil Nadu",
    category: "Crop & Seeds",
    coverage: "Tamil Nadu",
    benefit: "Certification supporting recognition of organic production status with subsidized inspection fees.",
    documentsCount: 2,
    description: "Organic certification programme listed by Tamil Nadu Agriculture Department.",
    officialUrl: "https://tanoca.org",
    eligibility: ["Organic farmers in Tamil Nadu"],
    documentsList: ["Aadhaar Card", "Farm History Sheet & Land Records"],
    howToApply: "Apply through Tamil Nadu Organic Certification Department (TNOCD)."
  },
  {
    id: "tn-kuruvai-package",
    icon: "🌱",
    title: "Kuruvai Special Package - 2026",
    state: "Tamil Nadu",
    category: "Crop & Seeds",
    coverage: "Tamil Nadu",
    benefit: "Benefits and components according to the 2026 Kuruvai Special Package announcement (free seeds, micronutrients, machine planting subsidy).",
    documentsCount: 2,
    description: "Special package announced by the Tamil Nadu Agriculture and Farmers Welfare Department for Kuruvai paddy cultivation.",
    officialUrl: "https://tnagrisnet.tn.gov.in",
    eligibility: ["Delta district farmers (Thanjavur, Tiruvarur, Nagapattinam, Mayiladuthurai, etc.)"],
    documentsList: ["Aadhaar Card", "Paddy Land Cultivation Record"],
    howToApply: "Collect coupons from Primary Agricultural Cooperative Societies (PACS) or Uzhavan App."
  },
  {
    id: "tn-nhm",
    icon: "🌳",
    title: "National Horticulture Mission (NHM)",
    state: "Tamil Nadu",
    category: "Horticulture",
    coverage: "Tamil Nadu",
    benefit: "Support according to the applicable horticulture component (fruit orchards, protected polyhouses, packhouses).",
    documentsCount: 2,
    description: "Horticulture development scheme listed in Tamil Nadu's official horticulture scheme list.",
    officialUrl: "https://tnhorticulture.tn.gov.in",
    eligibility: ["Growers of fruits, vegetables, flowers, spices, and plantation crops"],
    documentsList: ["Patta / Chitta", "Aadhaar Card"],
    howToApply: "Register on tnhorticulture.tn.gov.in."
  },
  {
    id: "tn-pdmc",
    icon: "💧",
    title: "Per Drop More Crop (PDMC)",
    state: "Tamil Nadu",
    category: "Irrigation",
    coverage: "Tamil Nadu",
    benefit: "Assistance according to the applicable micro-irrigation component.",
    documentsCount: 2,
    description: "Micro-irrigation and water-use-efficiency programme listed in Tamil Nadu's horticulture scheme list.",
    officialUrl: "https://tnhorticulture.tn.gov.in",
    eligibility: ["All farmers with irrigable land holdings"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply through local Horticulture Extension Officer."
  },
  {
    id: "tn-shds",
    icon: "🌳",
    title: "State Horticulture Development Scheme (SHDS)",
    state: "Tamil Nadu",
    category: "Horticulture",
    coverage: "Tamil Nadu",
    benefit: "Horticulture development support according to applicable components (seeds, grafts, shade nets).",
    documentsCount: 2,
    description: "State horticulture development programme implemented through TANHODA.",
    officialUrl: "https://tnhorticulture.tn.gov.in",
    eligibility: ["Horticulture farmers in non-NHM districts of Tamil Nadu"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply online at TANHODA portal."
  },
  {
    id: "tn-pm-rkvy",
    icon: "💰",
    title: "PM-Rashtriya Krishi Vikas Yojana (PM-RKVY)",
    state: "Tamil Nadu",
    category: "Financial Assistance",
    coverage: "Tamil Nadu",
    benefit: "Benefits depend on the approved component for infrastructure and crop productivity.",
    documentsCount: 2,
    description: "Agriculture and horticulture development programme listed by Tamil Nadu.",
    officialUrl: "https://tnagrisnet.tn.gov.in",
    eligibility: ["Farmer groups and progressive growers"],
    documentsList: ["Aadhaar Card", "Bank Account Details"],
    howToApply: "Contact District Agriculture Office."
  },

  // GUJARAT SCHEMES
  {
    id: "gj-nmeo",
    icon: "🌱",
    title: "NMEO - Oilseeds",
    state: "Gujarat",
    category: "Crop & Seeds",
    coverage: "Gujarat",
    benefit: "Assistance according to the applicable NMEO component (groundnut, sesame, mustard seed mini-kits).",
    documentsCount: 2,
    description: "Oilseed-related scheme component available through Gujarat's official farmer scheme system.",
    officialUrl: "https://ikhedut.gujarat.gov.in",
    eligibility: ["Farmers in Gujarat cultivating oilseed crops"],
    documentsList: ["7/12 & 8-A Land Records", "Aadhaar Card"],
    howToApply: "Apply online at i-Khedut Portal: ikhedut.gujarat.gov.in."
  },
  {
    id: "gj-st-sugarcane",
    icon: "💰",
    title: "Incentive Assistance to Scheduled Tribe Farmers for Sugarcane",
    state: "Gujarat",
    category: "Financial Assistance",
    coverage: "Gujarat",
    benefit: "Incentive assistance according to the official Gujarat scheme conditions.",
    documentsCount: 2,
    description: "State scheme providing incentive assistance to Scheduled Tribe farmers to increase area, production and productivity of sugarcane.",
    officialUrl: "https://ikhedut.gujarat.gov.in",
    eligibility: ["Scheduled Tribe (ST) category farmers cultivating sugarcane in Gujarat"],
    documentsList: ["Caste Certificate", "7/12 Land Records", "Aadhaar Card"],
    howToApply: "Apply on the i-Khedut portal during the scheme window."
  },
  {
    id: "gj-cop37-godowns",
    icon: "🚜",
    title: "COP-37 - Construction of New Godowns",
    state: "Gujarat",
    category: "Equipment",
    coverage: "Gujarat",
    benefit: "Assistance according to the applicable scheme guidelines (up to ₹50,000 subsidy on on-farm godowns).",
    documentsCount: 2,
    description: "Scheme for construction of new godowns to increase storage capacity for agricultural produce.",
    officialUrl: "https://ikhedut.gujarat.gov.in",
    eligibility: ["Individual farmers with minimum required land holding"],
    documentsList: ["7/12 Record", "Aadhaar Card", "Bank Passbook"],
    howToApply: "Apply online on i-Khedut Portal."
  },

  // HARYANA SCHEMES
  {
    id: "hr-dsr",
    icon: "🌱",
    title: "Direct Seeded Rice (DSR)",
    state: "Haryana",
    category: "Crop & Seeds",
    coverage: "Haryana",
    benefit: "Support according to the current Haryana DSR scheme guidelines (financial incentive of ₹4,000/acre for saving water).",
    documentsCount: 2,
    description: "Haryana programme promoting direct seeded rice cultivation.",
    officialUrl: "https://fasal.haryana.gov.in",
    eligibility: ["Farmers practicing DSR method registered on Meri Fasal Mera Byora"],
    documentsList: ["Meri Fasal Mera Byora Registration", "Aadhaar Card & Bank Details"],
    howToApply: "Register crop on fasal.haryana.gov.in portal."
  },
  {
    id: "hr-desi-cotton",
    icon: "🌱",
    title: "Desi Cotton Scheme",
    state: "Haryana",
    category: "Crop & Seeds",
    coverage: "Haryana",
    benefit: "Support according to the current Haryana scheme guidelines (incentive of ₹3,000/acre).",
    documentsCount: 2,
    description: "Haryana government scheme for Desi Cotton cultivation.",
    officialUrl: "https://fasal.haryana.gov.in",
    eligibility: ["Farmers in Haryana cultivating indigenous/desi cotton varieties"],
    documentsList: ["MFMB Registration", "Aadhaar Card"],
    howToApply: "Register on Meri Fasal Mera Byora."
  },
  {
    id: "hr-atma",
    icon: "🌱",
    title: "Support to State Extension Programmes for Extension Reforms (ATMA)",
    state: "Haryana",
    category: "Crop & Seeds",
    coverage: "Haryana",
    benefit: "Extension, training and farmer-support activities.",
    documentsCount: 2,
    description: "Agricultural extension programme supporting farmer groups, capacity building, exhibitions, Kisan Melas and farmer-scientist interactions.",
    officialUrl: "https://agriharyana.gov.in",
    eligibility: ["All farming households in Haryana"],
    documentsList: ["Aadhaar Card", "Parivar Pehchan Patra (PPP)"],
    howToApply: "Contact Block Agriculture Officer."
  },

  // BIHAR SCHEMES
  {
    id: "br-mechanization",
    icon: "🚜",
    title: "Agricultural Mechanization",
    state: "Bihar",
    category: "Equipment",
    coverage: "Bihar",
    benefit: "Mechanization support according to applicable Bihar scheme guidelines (up to 50-80% subsidy on farm implements).",
    documentsCount: 2,
    description: "Agricultural mechanization scheme listed by the Bihar Agriculture Department.",
    officialUrl: "https://farmech.bih.nic.in",
    eligibility: ["Registered farmers in Bihar DBT Agriculture Portal"],
    documentsList: ["DBT Registration Number", "LPC (Land Possession Certificate)"],
    howToApply: "Apply on OFMAS portal: farmech.bih.nic.in."
  },
  {
    id: "br-nhm",
    icon: "🌳",
    title: "National Horticulture Mission",
    state: "Bihar",
    category: "Horticulture",
    coverage: "Bihar",
    benefit: "Horticulture support according to applicable guidelines for fruits and vegetable cultivation.",
    documentsCount: 2,
    description: "Horticulture development scheme listed by Bihar Agriculture Department.",
    officialUrl: "https://horticulture.bihar.gov.in",
    eligibility: ["Farmers in selected NHM districts in Bihar"],
    documentsList: ["Aadhaar Card", "LPC / Land Records"],
    howToApply: "Apply at horticulture.bihar.gov.in."
  },
  {
    id: "br-cm-horticulture",
    icon: "🌳",
    title: "Chief Minister Horticulture Mission",
    state: "Bihar",
    category: "Horticulture",
    coverage: "Bihar",
    benefit: "Horticulture assistance according to current programme guidelines.",
    documentsCount: 2,
    description: "Bihar government horticulture programme.",
    officialUrl: "https://horticulture.bihar.gov.in",
    eligibility: ["Farmers across all 38 districts of Bihar"],
    documentsList: ["DBT Registration", "Aadhaar Card"],
    howToApply: "Register on Bihar Horticulture Portal."
  },
  {
    id: "br-micro-irrigation",
    icon: "💧",
    title: "National Micro Irrigation Mission Scheme",
    state: "Bihar",
    category: "Irrigation",
    coverage: "Bihar",
    benefit: "Micro-irrigation support according to applicable guidelines (up to 70% subsidy on drip/sprinkler).",
    documentsCount: 2,
    description: "Micro-irrigation scheme listed by Bihar Agriculture Department.",
    officialUrl: "https://horticulture.bihar.gov.in",
    eligibility: ["Farmers with assured water sources"],
    documentsList: ["LPC / Land Records", "Aadhaar Card"],
    howToApply: "Apply online on Bihar Horticulture Portal."
  },
  {
    id: "br-medicinal-plants",
    icon: "🌳",
    title: "National Medicinal Plants Mission Programme",
    state: "Bihar",
    category: "Horticulture",
    coverage: "Bihar",
    benefit: "Support according to applicable medicinal plant programme guidelines.",
    documentsCount: 2,
    description: "Medicinal plant development programme listed by Bihar Agriculture Department.",
    officialUrl: "https://horticulture.bihar.gov.in",
    eligibility: ["Farmers cultivating lemon grass, aloe vera, ashwagandha, etc."],
    documentsList: ["DBT Registration", "Land Record"],
    howToApply: "Submit application to District Horticulture Officer."
  },
  {
    id: "br-nfsm",
    icon: "🌱",
    title: "National Food Security Mission",
    state: "Bihar",
    category: "Crop & Seeds",
    coverage: "Bihar",
    benefit: "Support according to applicable NFSM components for wheat, pulses, and coarse cereals.",
    documentsCount: 2,
    description: "Food crop development programme listed by Bihar Agriculture Department.",
    officialUrl: "https://dbtagriculture.bihar.gov.in",
    eligibility: ["Farmers in notified NFSM districts of Bihar"],
    documentsList: ["DBT Registration Number", "Aadhaar Card"],
    howToApply: "Apply on BRAMAS portal via dbtagriculture.bihar.gov.in."
  },
  {
    id: "br-isopom",
    icon: "🌱",
    title: "Integrated Scheme on Oilseeds and Maize (ISOPOM)",
    state: "Bihar",
    category: "Crop & Seeds",
    coverage: "Bihar",
    benefit: "Support according to applicable crop and programme guidelines.",
    documentsCount: 2,
    description: "Oilseed and maize development programme listed by Bihar Agriculture Department.",
    officialUrl: "https://dbtagriculture.bihar.gov.in",
    eligibility: ["Maize and oilseed farmers in Bihar"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply on Bihar DBT Agriculture portal."
  },
  {
    id: "br-seed-production",
    icon: "🌱",
    title: "Seed Production Programme in Government Agricultural Farms",
    state: "Bihar",
    category: "Crop & Seeds",
    coverage: "Bihar",
    benefit: "Supports production and availability of agricultural seed.",
    documentsCount: 2,
    description: "Seed production programme listed by Bihar Agriculture Department.",
    officialUrl: "https://brbn.bihar.gov.in",
    eligibility: ["Seed grower farmers registered with Bihar Rajya Beej Nigam"],
    documentsList: ["Seed Certification Registration", "Aadhaar Card"],
    howToApply: "Apply at BRBN office or portal."
  },
  {
    id: "br-krishi-input",
    icon: "💰",
    title: "Krishi Input Anudaan",
    state: "Bihar",
    category: "Financial Assistance",
    coverage: "Bihar",
    benefit: "Agricultural input assistance according to the applicable Bihar guidelines (relief for drought/flood crop damages).",
    documentsCount: 2,
    description: "Agricultural input assistance scheme registered in the Bihar DBT scheme database.",
    officialUrl: "https://dbtagriculture.bihar.gov.in",
    eligibility: ["Farmers in flood or drought notified blocks who suffered >33% crop loss"],
    documentsList: ["DBT Registration Number", "LPC / Self Declaration"],
    howToApply: "Apply on dbtagriculture.bihar.gov.in during the relief window."
  },
  {
    id: "br-seed-distribution",
    icon: "🌱",
    title: "Seed Distribution Scheme",
    state: "Bihar",
    category: "Crop & Seeds",
    coverage: "Bihar",
    benefit: "Seed support according to current scheme conditions (home delivery of subsidized certified seeds).",
    documentsCount: 2,
    description: "Seed distribution scheme registered in Bihar's official DBT scheme database.",
    officialUrl: "https://brbn.bihar.gov.in",
    eligibility: ["All registered farmers in Bihar"],
    documentsList: ["DBT Registration Number", "Aadhaar Card"],
    howToApply: "Apply on BRBN Portal for home-delivery or PACS collection."
  },

  // ASSAM SCHEMES
  {
    id: "as-cmsguy",
    icon: "🚜",
    title: "Chief Minister Samagra Gramya Unnayan Yojana (CMSGUY)",
    state: "Assam",
    category: "Equipment",
    coverage: "Assam",
    benefit: "Support according to applicable programme components (70% subsidy on tractors to revenue villages).",
    documentsCount: 2,
    description: "Assam government programme supporting rural development and agricultural activities.",
    officialUrl: "https://mmcmgugy.assam.gov.in",
    eligibility: ["Registered farmer groups consisting of 8-10 adult members"],
    documentsList: ["Group Resolution Copy", "Members' Aadhaar Cards"],
    howToApply: "Apply to the District Level Committee headed by Deputy Commissioner."
  },
  {
    id: "as-rkvy",
    icon: "🌱",
    title: "Rashtriya Krishi Vikas Yojana (RKVY)",
    state: "Assam",
    category: "Crop & Seeds",
    coverage: "Assam",
    benefit: "Crop, input and agricultural development support according to applicable components.",
    documentsCount: 2,
    description: "Agricultural development programme implemented in Assam.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Farmers and FPOs in Assam"],
    documentsList: ["Aadhaar Card", "Land Document"],
    howToApply: "Apply through District Agriculture Officer (DAO)."
  },
  {
    id: "as-nfsm",
    icon: "🌱",
    title: "National Food Security Mission (NFSM)",
    state: "Assam",
    category: "Crop & Seeds",
    coverage: "Assam",
    benefit: "Crop development support according to applicable NFSM components.",
    documentsCount: 2,
    description: "Food crop production programme listed by Assam Agriculture Department.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Rice and pulse cultivators in Assam"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Contact Agriculture Development Officer (ADO) at the circle level."
  },
  {
    id: "as-nmsa",
    icon: "🌱",
    title: "National Mission for Sustainable Agriculture (NMSA)",
    state: "Assam",
    category: "Crop & Seeds",
    coverage: "Assam",
    benefit: "Support according to applicable sustainable agriculture components.",
    documentsCount: 2,
    description: "Sustainable agriculture programme listed by Assam Agriculture Department.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Farmers in rainfed and vulnerable agro-climatic zones"],
    documentsList: ["Aadhaar Card", "Land Document"],
    howToApply: "Apply through District Agriculture Office."
  },
  {
    id: "as-nmoop",
    icon: "🌱",
    title: "National Mission on Oil Seeds & Oil Palm (NMOOP)",
    state: "Assam",
    category: "Crop & Seeds",
    coverage: "Assam",
    benefit: "Support according to applicable crop components for mustard and oil palm cultivation.",
    documentsCount: 2,
    description: "Oilseed and oil-palm development programme listed by Assam Agriculture Department.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Farmers in identified districts of Assam"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Register with Block Agriculture Officer."
  },
  {
    id: "as-pmfby",
    icon: "🛡️",
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    state: "Assam",
    category: "Insurance",
    coverage: "Assam",
    benefit: "Insurance protection according to notified crops and current guidelines (only ₹1 token premium in Assam).",
    documentsCount: 2,
    description: "Crop insurance programme implemented in Assam.",
    officialUrl: "https://pmfby.gov.in",
    eligibility: ["Farmers cultivating notified crops (Sali paddy, Boro paddy, etc.)"],
    documentsList: ["Aadhaar Card", "Land Document / Jamabandi"],
    howToApply: "Apply at local CSC centre or through pmfby.gov.in."
  },
  {
    id: "as-pmksy",
    icon: "💧",
    title: "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)",
    state: "Assam",
    category: "Irrigation",
    coverage: "Assam",
    benefit: "Irrigation support according to applicable components (shallow tube wells, solar pumps).",
    documentsCount: 2,
    description: "Irrigation and water-use-efficiency programme implemented in Assam.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Individual farmers with cultivable plots"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply at the local Agriculture Development Office."
  },
  {
    id: "as-krishi-sajuli",
    icon: "🚜",
    title: "Mukhya Mantri Krishi Sa Sajuli Yozana",
    state: "Assam",
    category: "Equipment",
    coverage: "Assam",
    benefit: "Support according to applicable scheme guidelines (₹5,000 direct transfer for purchase of farm tools).",
    documentsCount: 2,
    description: "Agricultural equipment-oriented programme listed by Assam Agriculture Department.",
    officialUrl: "https://diragri.assam.gov.in",
    eligibility: ["Small and marginal farmers of Assam"],
    documentsList: ["Aadhaar Card", "Bank Passbook"],
    howToApply: "Apply through Gaon Panchayat Agriculture Committee."
  },
  {
    id: "as-apart",
    icon: "💰",
    title: "Assam Agribusiness & Rural Transformation Project (APART)",
    state: "Assam",
    category: "Financial Assistance",
    coverage: "Assam",
    benefit: "Value-chain, agribusiness and post-harvest support according to project components.",
    documentsCount: 2,
    description: "Agribusiness and rural transformation project supporting agricultural value chains and agribusiness development.",
    officialUrl: "https://arias.in",
    eligibility: ["FPOs, Farmer Interest Groups, and Agri-enterprises in 16 target districts"],
    documentsList: ["FPO Registration", "Project Proposal"],
    howToApply: "Apply to ARIAS Society / District Project Management Unit (DPMU)."
  },
  {
    id: "as-smam",
    icon: "🚜",
    title: "Sub-Mission on Agricultural Mechanization (SMAM)",
    state: "Assam",
    category: "Equipment",
    coverage: "Assam",
    benefit: "Access to farm machinery through applicable mechanization components.",
    documentsCount: 2,
    description: "Agricultural mechanization programme supporting machinery banks, custom hiring centres and farm machinery access.",
    officialUrl: "https://agrimachinery.nic.in",
    eligibility: ["Farmers and CHC groups in Assam"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Register on agrimachinery.nic.in."
  },

  // KERALA SCHEMES
  {
    id: "kl-rice-development",
    icon: "🌱",
    title: "Rice Development",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Rice cultivation and productivity support according to current state programme components (royalty of ₹3,000/ha for paddy owners).",
    documentsCount: 2,
    description: "State agriculture programme supporting rice development in Kerala.",
    officialUrl: "https://keralaharsham.gov.in",
    eligibility: ["Paddy land owners maintaining active paddy cultivation"],
    documentsList: ["Tax Receipt", "Aadhaar Card & Bank Account"],
    howToApply: "Register on AIMSKerala portal: aims.kerala.gov.in."
  },
  {
    id: "kl-soil-health",
    icon: "🌱",
    title: "Soil Health Management and Productivity Improvement",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Soil health and productivity improvement support (free lime/dolomite distribution).",
    documentsCount: 2,
    description: "Kerala state agriculture programme for soil health management and productivity improvement.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["All farmers having cultivable land in Kerala"],
    documentsList: ["Aadhaar Card", "Land Tax Receipt"],
    howToApply: "Contact local Krishi Bhavan."
  },
  {
    id: "kl-spices-dev",
    icon: "🌳",
    title: "Development of Spices",
    state: "Kerala",
    category: "Horticulture",
    coverage: "Kerala",
    benefit: "Spice development support according to programme guidelines for pepper, cardamom, ginger, and nutmeg.",
    documentsCount: 2,
    description: "Agricultural development programme supporting spice cultivation in Kerala.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Spice cultivators in Wayanad, Idukki, and hill tracts"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply to Krishi Bhavan in notified blocks."
  },
  {
    id: "kl-vegetable-dev",
    icon: "🌱",
    title: "Vegetable Development through Agriculture Department",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Vegetable production support according to current programme components (free vegetable seeds & grow-bag kits).",
    documentsCount: 2,
    description: "Kerala agriculture programme supporting vegetable development.",
    officialUrl: "https://aims.kerala.gov.in",
    eligibility: ["Commercial vegetable growers and rooftop farmers"],
    documentsList: ["Aadhaar Card", "Ration Card"],
    howToApply: "Register at local Krishi Bhavan before Onam/Vishu season."
  },
  {
    id: "kl-organic-farming",
    icon: "🌱",
    title: "Organic Farming and Safe-to-Eat Food Production",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Support for organic and safe agricultural production (Jaiva Keralam assistance).",
    documentsCount: 2,
    description: "Kerala state programme supporting organic farming and safe food production.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Certified organic cultivators and clusters"],
    documentsList: ["Aadhaar Card", "Certification Proof"],
    howToApply: "Apply through Krishi Bhavan."
  },
  {
    id: "kl-coconut-dev",
    icon: "🌳",
    title: "Coconut Development",
    state: "Kerala",
    category: "Horticulture",
    coverage: "Kerala",
    benefit: "Coconut development support according to applicable components (Keragramam package, root-wilt management).",
    documentsCount: 2,
    description: "State programme supporting coconut development.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Coconut farmers with contiguous holdings in Keragramam areas"],
    documentsList: ["Land Tax Receipt", "Aadhaar Card"],
    howToApply: "Register with local Keragramam committee at Krishi Bhavan."
  },
  {
    id: "kl-fruits-flowers",
    icon: "🌳",
    title: "Development of Fruits, Flowers and Medicinal Plants",
    state: "Kerala",
    category: "Horticulture",
    coverage: "Kerala",
    benefit: "Horticulture development support according to applicable components.",
    documentsCount: 2,
    description: "Kerala programme supporting fruits, flowers and medicinal plant development.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Growers of banana, mango, cut flowers, and medicinal plants"],
    documentsList: ["Aadhaar Card", "Land Records"],
    howToApply: "Apply via AIMS Kerala portal."
  },
  {
    id: "kl-millets",
    icon: "🌱",
    title: "Location Specific Schemes for Promotion of Millets",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Millet development support according to programme guidelines (incentive for ragi and bajra cultivation in Attappady).",
    documentsCount: 2,
    description: "Kerala programme supporting millet cultivation in applicable locations.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Tribal and traditional millet growers"],
    documentsList: ["Aadhaar Card", "Community Certificate"],
    howToApply: "Contact Attappady Tribal Agriculture Extension or local Krishi Bhavan."
  },
  {
    id: "kl-nawo-dhan",
    icon: "🌱",
    title: "Nawo-Dhan Scheme",
    state: "Kerala",
    category: "Crop & Seeds",
    coverage: "Kerala",
    benefit: "Support for agricultural use of suitable unused/fallow land according to programme rules (₹30,000/ha for fallow land paddy reclamation).",
    documentsCount: 2,
    description: "Kerala initiative aimed at bringing unused and fallow land into productive use.",
    officialUrl: "https://keralaagriculture.gov.in",
    eligibility: ["Farmers and Kudumbashree JLGs cultivating fallow land"],
    documentsList: ["Panchayat Fallow Land Clearance Certificate", "Aadhaar Card"],
    howToApply: "Apply through Krishi Bhavan."
  },
  {
    id: "kl-state-crop-insurance",
    icon: "🛡️",
    title: "Restructured State Crop Insurance Scheme",
    state: "Kerala",
    category: "Insurance",
    coverage: "Kerala",
    benefit: "Insurance support according to state crop insurance rules (covers 27 major crops including banana, pepper, cardamom).",
    documentsCount: 2,
    description: "Kerala state crop insurance programme covering specified agricultural crops against eligible losses.",
    officialUrl: "https://aims.kerala.gov.in",
    eligibility: ["All farmers growing any of the 27 notified crops in Kerala"],
    documentsList: ["Aadhaar Card", "Land Tax Receipt / Lease Agreement"],
    howToApply: "Enroll on AIMS Kerala portal: aims.kerala.gov.in."
  },

  // RAJASTHAN SCHEMES
  {
    id: "rj-natural-farming",
    icon: "🌱",
    title: "National Natural Farming Mission",
    state: "Rajasthan",
    category: "Crop & Seeds",
    coverage: "Rajasthan",
    benefit: "Support for sustainable farming and natural farming practices according to programme guidelines.",
    documentsCount: 2,
    description: "Natural farming programme included in Rajasthan's 2026-27 Agriculture Department budget output-outcome document.",
    officialUrl: "https://rajkisan.rajasthan.gov.in",
    eligibility: ["Farmers in selected clusters across Rajasthan"],
    documentsList: ["Jan Aadhaar Card", "Jamabandi (Land Record)"],
    howToApply: "Apply online at RajKisan Saathi portal: rajkisan.rajasthan.gov.in."
  },
  {
    id: "rj-pmfby",
    icon: "🛡️",
    title: "Pradhan Mantri Fasal Bima Yojana",
    state: "Rajasthan",
    category: "Insurance",
    coverage: "Rajasthan",
    benefit: "Crop risk protection according to PMFBY guidelines.",
    documentsCount: 2,
    description: "Crop insurance programme included in Rajasthan's Agriculture Department 2026-27 budget document.",
    officialUrl: "https://pmfby.gov.in",
    eligibility: ["Farmers cultivating notified Kharif/Rabi crops"],
    documentsList: ["Jan Aadhaar Card", "Sowing Certificate", "Jamabandi"],
    howToApply: "Enroll on RajKisan portal or nearest e-Mitra kiosk."
  },
  {
    id: "rj-agro-processing",
    icon: "💰",
    title: "Rajasthan Agro-Processing, Agri-Business and Agri Export Promotion Scheme",
    state: "Rajasthan",
    category: "Financial Assistance",
    coverage: "Rajasthan",
    benefit: "Assistance according to the applicable scheme guidelines (up to 50% capital subsidy, max ₹1 Crore for agro processing units).",
    documentsCount: 2,
    description: "Rajasthan scheme supporting agro-processing, agri-business and agricultural exports.",
    officialUrl: "https://rajkisan.rajasthan.gov.in",
    eligibility: ["Farmers, FPOs, and entrepreneurs setting up agro-processing units"],
    documentsList: ["Detailed Project Report", "Jan Aadhaar", "Land Ownership Proof"],
    howToApply: "Apply online on RajKisan Saathi portal."
  },

  // UTTARAKHAND SCHEMES
  {
    id: "uk-sc-st-villages",
    icon: "💰",
    title: "Agriculture Development Scheme in SC & ST Majority Villages",
    state: "Uttarakhand",
    category: "Financial Assistance",
    coverage: "Uttarakhand",
    benefit: "Agricultural development assistance according to applicable state guidelines.",
    documentsCount: 2,
    description: "State agriculture development scheme for SC and ST majority villages.",
    officialUrl: "https://agriculture.uk.gov.in",
    eligibility: ["Small & marginal farmers belonging to SC/ST categories in notified villages"],
    documentsList: ["Caste Certificate", "Aadhaar Card & Khatauni"],
    howToApply: "Contact Block Agriculture Development Officer."
  },
  {
    id: "uk-ima-village",
    icon: "🌱",
    title: "Veer Shiromani Madho Singh Bhandari IMA Village Scheme",
    state: "Uttarakhand",
    category: "Crop & Seeds",
    coverage: "Uttarakhand",
    benefit: "Support according to applicable state scheme guidelines (promoting aromatic and medicinal plants).",
    documentsCount: 2,
    description: "State-sector agriculture programme listed in Uttarakhand's official agriculture and horticulture scheme documentation.",
    officialUrl: "https://agriculture.uk.gov.in",
    eligibility: ["Farmers in hill districts of Uttarakhand"],
    documentsList: ["Aadhaar Card", "Land Records (Khatauni)"],
    howToApply: "Submit application to District Horticulture Officer."
  },
  {
    id: "uk-deendayal-kalyan",
    icon: "💰",
    title: "Deendayal Upadhayay Kissan Kalyan Yojna",
    state: "Uttarakhand",
    category: "Financial Assistance",
    coverage: "Uttarakhand",
    benefit: "Farmer welfare support according to applicable state guidelines (interest-free loans up to ₹3 Lakh for farming & SHGs).",
    documentsCount: 2,
    description: "Farmer welfare programme listed as a state-sector scheme in Uttarakhand agriculture documentation.",
    officialUrl: "https://cooperative.uk.gov.in",
    eligibility: ["All small and marginal farmers with active cooperative bank accounts"],
    documentsList: ["Aadhaar Card", "Land Records & Cooperative Society Passbook"],
    howToApply: "Apply at nearest District Cooperative Bank branch or PACS."
  },
  {
    id: "uk-farm-machinery-bank",
    icon: "🚜",
    title: "Shree Dev Suman Farm Machinery Bank Scheme",
    state: "Uttarakhand",
    category: "Equipment",
    coverage: "Uttarakhand",
    benefit: "Access to farm machinery according to applicable scheme guidelines (up to 80% subsidy for hill machinery banks).",
    documentsCount: 2,
    description: "Farm machinery bank scheme listed in Uttarakhand's agriculture scheme documentation.",
    officialUrl: "https://agriculture.uk.gov.in",
    eligibility: ["Registered Farmer Self-Help Groups (SHGs) and Gram Panchayats"],
    documentsList: ["SHG Registration", "Members' Aadhaar Cards"],
    howToApply: "Apply through Chief Agriculture Officer (CAO) in the district."
  },
  {
    id: "uk-crop-insurance",
    icon: "🛡️",
    title: "Crop Insurance Scheme",
    state: "Uttarakhand",
    category: "Insurance",
    coverage: "Uttarakhand",
    benefit: "Crop risk protection according to applicable insurance guidelines.",
    documentsCount: 2,
    description: "Crop insurance programme listed among Uttarakhand agriculture schemes.",
    officialUrl: "https://agriculture.uk.gov.in",
    eligibility: ["Farmers cultivating notified crops in hill and plains agro-climatic zones"],
    documentsList: ["Aadhaar Card", "Khatauni & Sowing Certificate"],
    howToApply: "Apply at local bank or CSC centre."
  },

  // GOA SCHEMES
  {
    id: "ga-quality-seed",
    icon: "🌱",
    title: "Assistance for Quality / Certified Seed",
    state: "Goa",
    category: "Crop & Seeds",
    coverage: "Goa",
    benefit: "Seed assistance according to the applicable Goa Agriculture Department scheme (up to 50% subsidy on certified paddy and pulse seeds).",
    documentsCount: 2,
    description: "Goa agriculture programme supporting availability of quality certified seed.",
    officialUrl: "https://agri.goa.gov.in",
    eligibility: ["Registered Krishi Card holder farmers in Goa"],
    documentsList: ["Krishi Card", "Aadhaar Card"],
    howToApply: "Apply at Zonal Agriculture Office (ZAO) of the respective taluka."
  },
  {
    id: "ga-sugarcane-price",
    icon: "💰",
    title: "Assured Price for Sugarcane",
    state: "Goa",
    category: "Financial Assistance",
    coverage: "Goa",
    benefit: "Price support according to the applicable Goa government scheme (assured support price above FRP for sugarcane).",
    documentsCount: 2,
    description: "Goa agriculture support programme for assured price of sugarcane produce.",
    officialUrl: "https://agri.goa.gov.in",
    eligibility: ["Sugarcane growers in Goa holding valid Krishi Cards"],
    documentsList: ["Krishi Card", "Weighment Slips & Bank Account Details"],
    howToApply: "Submit claims to Zonal Agriculture Office."
  },
  {
    id: "ga-paddy-price",
    icon: "💰",
    title: "Assured Price for Paddy",
    state: "Goa",
    category: "Financial Assistance",
    coverage: "Goa",
    benefit: "Price support according to applicable government conditions (assured price of ₹20/kg for paddy sold to authorized agencies).",
    documentsCount: 2,
    description: "Goa programme providing support towards an assured price for paddy sold through authorised procurement agencies.",
    officialUrl: "https://agri.goa.gov.in",
    eligibility: ["Goan farmers selling paddy through Goa State Horticultural Corporation or PACS"],
    documentsList: ["Krishi Card", "Procurement Agency Receipt"],
    howToApply: "Claim through Zonal Agriculture Office."
  },
  {
    id: "ga-alsando-price",
    icon: "🌱",
    title: "Assured Price for Alsando Crops",
    state: "Goa",
    category: "Crop & Seeds",
    coverage: "Goa",
    benefit: "Price support according to applicable programme conditions (assured price of ₹150/kg for traditional Alsando cowpea).",
    documentsCount: 2,
    description: "Goa programme supporting assured price for Alsando crops sold to cooperative societies.",
    officialUrl: "https://agri.goa.gov.in",
    eligibility: ["Farmers cultivating indigenous Goa Alsando crop with Krishi Card"],
    documentsList: ["Krishi Card", "Cooperative Sale Receipt"],
    howToApply: "Submit claim through local Zonal Agriculture Office."
  },
  {
    id: "ga-seed-minikits",
    icon: "🌱",
    title: "Distribution of Seed Mini Kits",
    state: "Goa",
    category: "Crop & Seeds",
    coverage: "Goa",
    benefit: "Seed kits for applicable crops according to scheme conditions (free distribution of high-yielding variety seed minikits).",
    documentsCount: 2,
    description: "Goa Agriculture Department programme for distribution of improved seed varieties.",
    officialUrl: "https://agri.goa.gov.in",
    eligibility: ["All Krishi Card holders cultivating vegetables, pulses, and oilseeds"],
    documentsList: ["Krishi Card", "Aadhaar Card"],
    howToApply: "Collect kits from taluka Zonal Agriculture Office."
  },
  {
    id: "krishi-bhagya",
    icon: "💧",
    title: "Krishi Bhagya Scheme",
    state: "Karnataka",
    category: "Irrigation",
    coverage: "Karnataka",
    benefit: "80% to 90% subsidy for construction of farm ponds (Krishi Honda), polythene lining, pump sets, and micro-irrigation.",
    documentsCount: 4,
    description: "Karnataka state flagship programme for sustainable dryland agriculture through rainwater harvesting and micro-irrigation.",
    officialUrl: "https://raitamitra.karnataka.gov.in",
    eligibility: ["Dryland and rainfed farmers in designated drought-prone taluks", "Hold valid RTC / Pahani land records"],
    documentsList: ["Aadhaar Card", "RTC / Pahani Land Record", "Bank Passbook", "Caste Certificate (if SC/ST for 90% subsidy)"],
    howToApply: "Apply at Raitha Samparka Kendra (RSK) or submit online application via the Karnataka Raita Mitra portal."
  },
  {
    id: "raitha-siri",
    icon: "🌱",
    title: "Raitha Siri Scheme",
    state: "Karnataka",
    category: "Crop & Seeds",
    coverage: "Karnataka",
    benefit: "Direct incentive of ₹10,000 per hectare (up to 2 hectares) deposited via DBT into farmers' bank accounts.",
    documentsCount: 3,
    description: "Incentive scheme to promote the cultivation of nutritious minor millets including Ragi, Foxtail, Little, Kodo, and Barnyard millets.",
    officialUrl: "https://raitamitra.karnataka.gov.in",
    eligibility: ["Farmers cultivating notified millet varieties in Karnataka", "Verified crop entry on the Karnataka FRUITS portal"],
    documentsList: ["Aadhaar Card", "FRUITS FID Number", "Land Record (Pahani/RTC)"],
    howToApply: "Register on the FRUITS portal (fruits.karnataka.gov.in) and register millet acreage through the village Raitha Samparka Kendra."
  },
  {
    id: "ganga-kalyana",
    icon: "💧",
    title: "Ganga Kalyana Scheme",
    state: "Karnataka",
    category: "Irrigation",
    coverage: "Karnataka",
    benefit: "Free individual or community borewell drilling with submersible pump sets and electrification worth up to ₹3.5 Lakh.",
    documentsCount: 5,
    description: "Irrigation development scheme providing individual and community open/bore wells with energized pump sets for small and marginal farmers.",
    officialUrl: "https://kmdc.karnataka.gov.in",
    eligibility: ["Small and marginal farmers belonging to SC, ST, OBC, or religious minorities", "Minimum landholding of 1.5 acres (or 2-5 acres for community schemes)"],
    documentsList: ["Aadhaar Card", "RTC / Land Record", "Caste & Income Certificate", "BPL Ration Card", "Small Farmer Certificate from Tahsildar"],
    howToApply: "Submit application through Seva Sindhu portal (sevasindhu.karnataka.gov.in) during the annual application window."
  },
  {
    id: "namo-shetkari",
    icon: "💰",
    title: "Namo Shetkari Mahasanman Nidhi Yojana",
    state: "Maharashtra",
    category: "Financial Assistance",
    coverage: "Maharashtra",
    benefit: "₹6,000 per year direct income support in three ₹2,000 installments, provided by Maharashtra Govt on top of PM-KISAN.",
    documentsCount: 3,
    description: "Maharashtra state DBT scheme providing financial relief to farmers in addition to the central PM-KISAN benefit (total ₹12,000/yr).",
    officialUrl: "https://mahadbt.maharashtra.gov.in",
    eligibility: ["All farmers in Maharashtra who are approved beneficiaries of central PM-KISAN", "Land ownership updated on 7/12 land records", "e-KYC verified"],
    documentsList: ["Aadhaar Card", "7/12 & 8A Land Extract", "Aadhaar-seeded Bank Account Details"],
    howToApply: "Automatically linked for eligible PM-KISAN beneficiaries in Maharashtra via the MahaDBT farmer portal."
  },
  {
    id: "dr-punjabrao-deshmukh",
    icon: "💳",
    title: "Dr. Punjabrao Deshmukh Interest Concession Scheme",
    state: "Maharashtra",
    category: "Credit & Loans",
    coverage: "Maharashtra",
    benefit: "100% interest concession (effective 0% interest) on short-term crop loans up to ₹3 Lakh paid within the due date.",
    documentsCount: 4,
    description: "Interest subvention scheme ensuring zero-interest crop credit for disciplined farmers repaying within the bank's scheduled timeframe.",
    officialUrl: "https://krishi.maharashtra.gov.in",
    eligibility: ["Farmers who have availed short-term crop loan from DCCB, Commercial Banks, or RRBs", "Full loan repayment on or before the due date"],
    documentsList: ["Kisan Credit Card / Loan Passbook", "No-Dues / Timely Repayment Certificate", "7/12 Land Record", "Aadhaar Card"],
    howToApply: "Claimed automatically through the lending bank branch upon full repayment of crop loan before the specified due date."
  },
  {
    id: "magel-tyala-shet-tale",
    icon: "💧",
    title: "Magel Tyala Shet Tale (Farm Ponds on Demand)",
    state: "Maharashtra",
    category: "Irrigation",
    coverage: "Maharashtra",
    benefit: "Direct capital grant subsidy of up to ₹50,000 for digging and plastic lining of on-farm water storage ponds.",
    documentsCount: 4,
    description: "Demand-driven farm pond scheme to harvest runoff rainwater and ensure protective irrigation during critical crop growth stages.",
    officialUrl: "https://mahadbt.maharashtra.gov.in",
    eligibility: ["Farmers holding at least 0.60 hectare (1.5 acres) of cultivable land", "Land must be technically suitable for water harvesting"],
    documentsList: ["Aadhaar Card", "7/12 and 8A Extracts", "Bank Passbook", "Self-declaration of ownership"],
    howToApply: "Register on the MahaDBT Farmer Schemes portal (mahadbt.maharashtra.gov.in) under Agriculture department."
  },
  {
    id: "rythu-bandhu",
    icon: "💰",
    title: "Rythu Bandhu / Rythu Bharosa",
    state: "Telangana",
    category: "Financial Assistance",
    coverage: "Telangana",
    benefit: "Investment support of ₹10,000 to ₹15,000 per acre per year (₹5,000 to ₹7,500/season) directly credited to farmer accounts.",
    documentsCount: 3,
    description: "Flagship agriculture investment support scheme of Telangana to purchase seeds, fertilizers, and cover labor expenses.",
    officialUrl: "https://rythubandhu.telangana.gov.in",
    eligibility: ["All agricultural land-owning patta holders recorded on the Dharani portal in Telangana"],
    documentsList: ["Pattadar Passbook / Dharani Title Deed", "Aadhaar Card", "Aadhaar-linked Bank Passbook"],
    howToApply: "Land records digitized on the Dharani portal are automatically mapped; verify status at local Agriculture Extension Officer (AEO) office."
  },
  {
    id: "rythu-bima",
    icon: "🛡️",
    title: "Rythu Bima (Farmers Group Life Insurance)",
    state: "Telangana",
    category: "Insurance",
    coverage: "Telangana",
    benefit: "₹5,00,000 comprehensive life insurance claim deposited directly to the nominee within 10 days of the farmer's demise.",
    documentsCount: 4,
    description: "100% state-funded group life insurance protection for farmer families, regardless of cause of death (natural or accidental).",
    officialUrl: "https://rythubima.telangana.gov.in",
    eligibility: ["Pattadar landholding farmers aged between 18 and 59 years", "Enrolled via Agriculture Extension Officer"],
    documentsList: ["Pattadar Passbook", "Aadhaar Card of Farmer & Nominee", "Nominee Bank Passbook", "Death Certificate & Claim Form (in event of claim)"],
    howToApply: "Nominee submits the claim form and death certificate to the local Agriculture Extension Officer (AEO)."
  },
  {
    id: "up-kisan-durghatna",
    icon: "🛡️",
    title: "Mukhyamantri Krishak Durghatna Kalyan Yojana",
    state: "Uttar Pradesh",
    category: "Insurance",
    coverage: "Uttar Pradesh",
    benefit: "Financial assistance of ₹5 Lakh to the farmer's family in case of accidental death or permanent disability while on duty.",
    documentsCount: 4,
    description: "Uttar Pradesh government insurance and welfare scheme protecting farmers, sharecroppers, and farm laborers against work accidents.",
    officialUrl: "https://upagriculture.com",
    eligibility: ["Farmers, co-sharers, and registered lease/tenant workers in Uttar Pradesh aged 18 to 70 years"],
    documentsList: ["Aadhaar Card", "Khatauni Land Record", "FIR / Post-mortem / Disability Report", "Nominee Bank Account"],
    howToApply: "Submit the claim application to the respective District Magistrate / Sub-Divisional Magistrate (SDM) within 45 days of occurrence."
  },
  {
    id: "up-free-solar-pump",
    icon: "☀️",
    title: "UP PM-KUSUM Solar Pump Scheme",
    state: "Uttar Pradesh",
    category: "Solar & Energy",
    coverage: "Uttar Pradesh",
    benefit: "60% to 70% combined central and state capital subsidy for installing 2 HP, 3 HP, 5 HP, 7.5 HP, and 10 HP solar pumps.",
    documentsCount: 4,
    description: "Scheme to replace high-cost diesel pumps and electric tube-wells with grid-independent solar pumping units for clean irrigation.",
    officialUrl: "https://upagriculture.com",
    eligibility: ["Farmers having confirmed borewell / tubewell on their agricultural land in Uttar Pradesh"],
    documentsList: ["Aadhaar Card", "Khatauni Land Record", "Bank Passbook", "Affidavit of boring availability"],
    howToApply: "Book online token at upagriculture.com -> Krishi Yantra / Solar Pump Booking; deposit farmer share via bank challan."
  },
  {
    id: "punjab-crm-subsidy",
    icon: "🚜",
    title: "Crop Residue Management (CRM) Machinery Subsidy",
    state: "Punjab",
    category: "Equipment",
    coverage: "Punjab",
    benefit: "50% individual subsidy and 80% Custom Hiring Centre subsidy on Super Seeder, Happy Seeder, Baler, and Mulcher.",
    documentsCount: 4,
    description: "Punjab government mechanized agriculture mission to facilitate in-situ management of paddy straw and curb farm fires.",
    officialUrl: "https://agrimachinerypb.com",
    eligibility: ["Individual farmers, cooperative societies, and Farmer Producer Organizations (FPOs) in Punjab"],
    documentsList: ["Aadhaar Card", "Fard / Land Record", "Bank Passbook", "Tractor Registration Certificate (RC)"],
    howToApply: "Apply online at agrimachinerypb.com during the departmental scheme opening notice."
  },
  {
    id: "punjab-paani-bachao",
    icon: "💧",
    title: "Paani Bachao, Paise Kamao (PBPK)",
    state: "Punjab",
    category: "Irrigation",
    coverage: "Punjab",
    benefit: "Direct cash incentive of ₹4.00 per kilowatt-hour deposited into farmer bank accounts for groundwater electricity saved.",
    documentsCount: 3,
    description: "Voluntary water conservation initiative rewarding farmers for prudent groundwater extraction through smart meter tracking.",
    officialUrl: "https://pspcl.in",
    eligibility: ["Agricultural tubewell consumers under designated PSPCL feeders in Punjab"],
    documentsList: ["Aadhaar Card", "PSPCL Tubewell Electricity Account", "Bank Account Details"],
    howToApply: "Enroll through the local PSPCL sub-divisional office or the Punjab State Power Corporation portal."
  },
  {
    id: "mp-kisan-kalyan",
    icon: "💰",
    title: "Mukhyamantri Kisan Kalyan Yojana",
    state: "Madhya Pradesh",
    category: "Financial Assistance",
    coverage: "Madhya Pradesh",
    benefit: "Additional financial aid of ₹6,000 per year in two installments deposited via DBT, over and above PM-KISAN (total ₹12,000/yr).",
    documentsCount: 3,
    description: "Madhya Pradesh government income support scheme complementing PM-KISAN for all registered landholding agriculturists.",
    officialUrl: "https://saara.mp.gov.in",
    eligibility: ["All PM-KISAN verified farmers in Madhya Pradesh holding agricultural land"],
    documentsList: ["Aadhaar Card", "Samagra ID", "Khasra / B-1 Land Record"],
    howToApply: "Automatic enrollment through the SAARA (Smart Application for Agricultural Revenue Activities) portal."
  },
  {
    id: "mp-bhavantar-bhugtan",
    icon: "💰",
    title: "Bhavantar Bhugtan Yojana (Price Deficit Scheme)",
    state: "Madhya Pradesh",
    category: "Financial Assistance",
    coverage: "Madhya Pradesh",
    benefit: "Compensates the deficit between the government Minimum Support Price (MSP) and the lower APMC mandi sale rate.",
    documentsCount: 4,
    description: "Price deficiency payment scheme protecting farmers from distress sales of soybean, groundnut, maize, and pulses during market gluts.",
    officialUrl: "https://e-uparjan.nic.in",
    eligibility: ["Registered farmers in Madhya Pradesh selling notified crops in licensed Krishi Upaj Mandis"],
    documentsList: ["e-Uparjan Registration Slip", "Aadhaar Card", "Mandi Sale Slip (Anubandh Patra)", "Bank Passbook"],
    howToApply: "Register on e-Uparjan portal prior to harvest and present registration receipt while trading at APMC mandi."
  },
  {
    id: "wb-krishak-bandhu",
    icon: "💰",
    title: "Krishak Bandhu (Natun) Scheme",
    state: "West Bengal",
    category: "Financial Assistance",
    coverage: "West Bengal",
    benefit: "Direct assistance of ₹10,000 per year per acre in two installments (Kharif & Rabi) + ₹2,00,000 death benefit for farmer families.",
    documentsCount: 4,
    description: "Flagship farmer welfare initiative of West Bengal providing assured financial assistance and social security to all cultivators.",
    officialUrl: "https://krishakbandhu.wb.gov.in",
    eligibility: ["All farmers possessing cultivable land including recorded Bhagchasis (sharecroppers) in West Bengal"],
    documentsList: ["Aadhaar Card / Voter ID", "RoR / Khatian Land Record", "Bank Passbook", "Mobile Number"],
    howToApply: "Apply at the local Assistant Director of Agriculture (ADA) office or online at krishakbandhu.wb.gov.in."
  },
  {
    id: "wb-bangla-shasya-bima",
    icon: "🛡️",
    title: "Bangla Shasya Bima (BSB)",
    state: "West Bengal",
    category: "Insurance",
    coverage: "West Bengal",
    benefit: "100% state-funded crop insurance with zero premium payable by farmers for all major seasonal food and oilseed crops.",
    documentsCount: 4,
    description: "Comprehensive crop insurance programme operated by the Government of West Bengal where the entire farmer premium is borne by the state.",
    officialUrl: "https://banglashasyabima.net",
    eligibility: ["All landholders, sharecroppers, and tenant farmers cultivating notified crops in West Bengal"],
    documentsList: ["Aadhaar Card", "Khatian / Patta / Bhagchasi Certificate", "Crop Sowing Certificate by Pradhan", "Bank Passbook"],
    howToApply: "Enroll through the nearest Gram Panchayat, BDO Office, or designated camps during seasonal enrollment windows."
  },
  {
    id: "odisha-kalia",
    icon: "💰",
    title: "KALIA (Krushak Assistance for Livelihood and Income Augmentation)",
    state: "Odisha",
    category: "Financial Assistance",
    coverage: "Odisha",
    benefit: "Financial assistance of ₹10,000/year for small & marginal farmers and ₹12,500 for landless agricultural households.",
    documentsCount: 3,
    description: "Holistic farmer livelihood support programme encompassing input assistance, landless livelihood assistance, and life insurance.",
    officialUrl: "https://kalia.odisha.gov.in",
    eligibility: ["Small and marginal farmers or landless agricultural households in Odisha", "Not an income-tax payer"],
    documentsList: ["Aadhaar Card", "Ration Card (BPL/AAY)", "Bank Passbook with IFSC"],
    howToApply: "Check name on the KALIA portal or apply via Gram Panchayat KALIA nodal officer."
  },
  {
    id: "odisha-balaram",
    icon: "💳",
    title: "BALARAM Scheme",
    state: "Odisha",
    category: "Credit & Loans",
    coverage: "Odisha",
    benefit: "Collateral-free agricultural loans up to ₹50,000 per member delivered through Joint Liability Groups (JLGs).",
    documentsCount: 3,
    description: "Pioneering state scheme delivering institutional credit to 7 lakh landless cultivators, sharecroppers, and oral lessees.",
    officialUrl: "https://agri.odisha.gov.in",
    eligibility: ["Landless tenant farmers and sharecroppers organized in Joint Liability Groups (JLGs) of 5 members in Odisha"],
    documentsList: ["Aadhaar Card", "JLG Group Agreement", "Bank Account Details"],
    howToApply: "Form a 5-member JLG with guidance from the local Krushak Sathi / VAW and apply through Primary Agricultural Credit Societies (PACS)."
  },
  {
    id: "hp-prakritik-kheti",
    icon: "🌱",
    title: "Prakritik Kheti Khushhal Kisan Yojana",
    state: "Himachal Pradesh",
    category: "Crop & Seeds",
    coverage: "Himachal Pradesh",
    benefit: "Free natural farming certification, indigenous cow purchase subsidy of ₹25,000, and 80% plastic drum input subsidy.",
    documentsCount: 3,
    description: "Mission promoting Subhash Palekar Natural Farming (SPNF) to reduce input costs and eliminate agrochemicals across mountain farms.",
    officialUrl: "https://spnfhp.nic.in",
    eligibility: ["Farmers and orchardists in Himachal Pradesh committed to chemical-free natural farming"],
    documentsList: ["Aadhaar Card", "Bonafide Himachali Certificate", "Land Revenue Record (Jamabandi)"],
    howToApply: "Register with the Block Project Manager (ATMA) at the block agriculture office."
  },
  {
    id: "pm-kusum",
    icon: "☀️",
    title: "PM-KUSUM (Kisan Urja Suraksha evam Utthaan Mahabhiyan)",
    state: "All India",
    category: "Solar & Energy",
    coverage: "All India",
    benefit: "Up to 60% capital subsidy (30% central + 30% state) for off-grid stand-alone solar agricultural pump sets.",
    documentsCount: 5,
    description: "National initiative enabling energy independence for farmers by providing solarized irrigation pumps and solar power generation.",
    officialUrl: "https://pmkusum.mnre.gov.in",
    eligibility: ["Individual farmers, water user associations, and farmer producer groups across India", "Land suitable for pump installation"],
    documentsList: ["Aadhaar Card", "Land Ownership Record (Khasra/Khatauni)", "Bank Account Details", "Electricity Bill (for grid-connected pumps)", "Boring Certificate"],
    howToApply: "Apply through your respective State Nodal Renewable Energy Agency (e.g., TEDA, KREDL, MEDA, UPNEDA, HAREDA)."
  },
  {
    id: "kcc-animal-husbandry",
    icon: "🐄",
    title: "Kisan Credit Card for Animal Husbandry & Dairy",
    state: "All India",
    category: "Credit & Loans",
    coverage: "All India",
    benefit: "Working capital credit limit up to ₹2,00,000 at a low subsidized interest rate of 4% per annum with timely repayment.",
    documentsCount: 4,
    description: "Extension of KCC facility to livestock, dairy, sheep/goat, and poultry farmers for meeting recurring feed and veterinary expenses.",
    officialUrl: "https://dahd.nic.in",
    eligibility: ["Farmers, dairy owners, and individual livestock breeders having cattle/buffalo/goats/poultry"],
    documentsList: ["Aadhaar Card", "Proof of Livestock Possession / Shed Ownership", "Bank Passbook", "No-Dues Certificate"],
    howToApply: "Submit the simplified Animal Husbandry KCC application form at any Commercial Bank, RRB, or Cooperative Bank branch."
  },
  {
    id: "pmmsy",
    icon: "🐟",
    title: "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
    state: "All India",
    category: "Financial Assistance",
    coverage: "All India",
    benefit: "40% capital subsidy for general category and 60% for SC, ST, and Women beneficiaries for fish ponds, biofloc, and hatchery units.",
    documentsCount: 5,
    description: "Flagship scheme for focused and sustainable development of the fisheries and aquaculture sector in marine and inland waters.",
    officialUrl: "https://pmmsy.dof.gov.in",
    eligibility: ["Fishers, fish farmers, self-help groups, and fisheries cooperatives across all states and UTs"],
    documentsList: ["Aadhaar Card", "Land / Water Body Lease or Ownership Proof", "Detailed Project Report (DPR)", "Bank Account Details", "Caste / Gender Certificate"],
    howToApply: "Submit DPR and application to the District Fisheries Officer (DFO) or apply online at pmmsy.dof.gov.in."
  },
];
